import os
from datetime import datetime
import logging

logger = logging.getLogger(__name__)

def save_to_obsidian(content: str, summary: str, metadata: dict):
    """
    将分析结果持久化为 Obsidian 中的 Markdown 文件。
    路径：obsidian/captured_insights/
    """
    # 定义保存目录 (相对于 project_code 的上一级 obsidian 目录)
    base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    save_path = os.path.join(base_dir, "captured_insights")
    
    if not os.path.exists(save_path):
        os.makedirs(save_path)
        logger.info(f"创建捕获目录: {save_path}")

    # 构造文件名 (时间戳 + 摘要前缀)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_summary = "".join([c for c in summary[:15] if c.isalnum() or c in " _-"]).strip()
    filename = f"Insight_{timestamp}_{safe_summary}.md"
    file_full_path = os.path.join(save_path, filename)

    # 构造 Markdown 内容 (包含 YAML 元数据)
    tags = " ".join([f"#{t}" for t in metadata.get("keywords", [])])
    md_content = f"""---
id: {timestamp}
source: {metadata.get("source", "mobile")}
tags: {tags}
---

# {summary}

> [!NOTE] 自动摘要
> {summary}

## 原始输入
{content}

---
*Generated by Project Sphere at {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}*
"""

    with open(file_full_path, "w", encoding="utf-8") as f:
        f.write(md_content)
    
    logger.info(f"物理文件已持久化至 Obsidian: {filename}")
    return filename
